version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - ./docker/pgadmin.env
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./docker/backend.env
    depends_on:
      - postgres
    networks:
      - backend-network
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "8080:3000"
    env_file:
      - ./docker/frontend.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network


networks:
  backend-network:
    driver: bridge
  app-network:
    driver: bridge

volumes:
  postgres_data:
